#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Cyril - 28/01/2014
baseoid = ".1.3.6.1.4.1.890.1.6.22.1.2"
suboid = "0"

def inventory_zywall_zld_ram(info):
    if len(info) > 0:
        return [ (None, (warn, crit) ) ]

def check_zywall_zld_ram(item, _no_params, info):
   warn = 70
   crit = 90
   value = int(info[0][0])
   perfdata = [ ("sys ram usage", value, warn, crit) ]
   if value > crit:
           return (2, "RAM: %i" % value, perfdata)
   elif value > warn:
           return (1, "RAM: %i" % value, perfdata)
   else:
           return (0, "RAM: %i" % value, perfdata)

check_info["zywall_zld_ram"] = {
        "check_function"        : check_zywall_zld_ram,
        "service_description"   : "Zywall ZLD RAM usage",
        "snmp_info"             : ( baseoid, [ suboid ] ),
        "has_perfdata"          : True,
        "inventory_function"    : inventory_zywall_zld_ram,
        }

snmp_scan_functions["zywall_zld_ram"] = \
	lambda oid: "zywall usg" in oid(".1.3.6.1.2.1.1.1.0").lower()
