#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Cyril - 28/01/2014
# Modele pour check snmp d'un seul OID. par exemple .1.3.6.1.2.1.4.5.0
# Adaptation  :
# Découper l'OID en deux, ici ".1.3.6.1.2.1.4.5" et "0" . Modifer baseoid et suboid
# ajuster crit et warn
# remplacer "zywall_zld_sessions" dans le nom des fonctions et dans les chaines

# OID a surveiller
baseoid = ".1.3.6.1.4.1.890.1.6.22.1.6"
suboid = "0"

def inventory_zywall_zld_sessions(info):
    if len(info) > 0:
        return [ (None, (warn, crit) ) ]

def check_zywall_zld_sessions(item, _no_params, info):
   # Valeur warn si dépassée
   warn = 10000
   # Valeur crit si dépassé
   crit = 20000
   value = int(info[0][0])
   perfdata = [ ("sessions", value, warn, crit) ]
   if value > crit:
           return (2, "Sessions: %i" % value, perfdata)
   elif value > warn:
           return (1, "Sessions: %i" % value, perfdata)
   else:
           return (0, "Sessions: %i" % value, perfdata)

check_info["zywall_zld_sessions"] = {
        "check_function"        : check_zywall_zld_sessions,
        "service_description"   : "Zywall ZLD active sessions",
        "snmp_info"             : ( baseoid, [ suboid ] ),
        "has_perfdata"          : True,
        "inventory_function"    : inventory_zywall_zld_sessions,
        }

snmp_scan_functions["zywall_zld_sessions"] = \
	lambda oid: "zywall usg" in oid(".1.3.6.1.2.1.1.1.0").lower()
